<?php

/**
 * @file
 * Primary module hooks for Open Referral module.
 */

use Drupal\localgov_openreferral\Entity\PropertyMappingInterface;
use Drupal\localgov_openreferral\SearchApiIndexConfig;

/**
 * Implements hook_entity_insert().
 */
function localgov_openreferral_localgov_openreferral_mapping_insert(PropertyMappingInterface $map) {
  if ($map->getPublicType() == 'service') {
    \Drupal::service('class_resolver')
      ->getInstanceFromDefinition(SearchApiIndexConfig::class)
      ->addToServicesIndex($map);
  }
}

/**
 * Implements hook_entity_delete().
 */
function localgov_openreferral_localgov_openreferral_mapping_delete(PropertyMappingInterface $map) {
  if ($map->mappedEntityType() == 'node') {
    \Drupal::service('class_resolver')
      ->getInstanceFromDefinition(SearchApiIndexConfig::class)
      ->removeFromServicesIndex($map);
  }
}
